# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {E:/Especializacion_fiuba/CLP/trabajo final/FIR/sintesis/filter/filter.cache/wt} [current_project]
set_property parent.project_path {E:/Especializacion_fiuba/CLP/trabajo final/FIR/sintesis/filter/filter.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-z7-10:part0:1.1 [current_project]
set_property ip_output_repo {e:/Especializacion_fiuba/CLP/trabajo final/FIR/sintesis/filter/filter.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {E:/Especializacion_fiuba/CLP/trabajo final/FIR/src/FIR_Pkg.vhd}
  {E:/Especializacion_fiuba/CLP/trabajo final/FIR/src/acum_fase.vhd}
  {E:/Especializacion_fiuba/CLP/trabajo final/FIR/src/adder.vhd}
  {E:/Especializacion_fiuba/CLP/trabajo final/FIR/src/shift_register.vhd}
  {E:/Especializacion_fiuba/CLP/trabajo final/FIR/src/multiplier.vhd}
  {E:/Especializacion_fiuba/CLP/trabajo final/FIR/src/filter.vhd}
  {E:/Especializacion_fiuba/CLP/trabajo final/FIR/src/generate_enable.vhd}
  {E:/Especializacion_fiuba/CLP/trabajo final/FIR/src/nco.vhd}
  {E:/Especializacion_fiuba/CLP/trabajo final/FIR/src/sin_cos.vhd}
  {E:/Especializacion_fiuba/CLP/trabajo final/FIR/src/sin_rom.vhd}
  {E:/Especializacion_fiuba/CLP/trabajo final/FIR/src/filter_VIO.vhd}
}
read_ip -quiet {{e:/Especializacion_fiuba/CLP/trabajo final/FIR/sintesis/filter/filter.srcs/sources_1/ip/vio_0/vio_0.xci}}
set_property used_in_implementation false [get_files -all {{e:/Especializacion_fiuba/CLP/trabajo final/FIR/sintesis/filter/filter.srcs/sources_1/ip/vio_0/vio_0.xdc}}]
set_property used_in_implementation false [get_files -all {{e:/Especializacion_fiuba/CLP/trabajo final/FIR/sintesis/filter/filter.srcs/sources_1/ip/vio_0/vio_0_ooc.xdc}}]

read_ip -quiet {{e:/Especializacion_fiuba/CLP/trabajo final/FIR/sintesis/filter/filter.srcs/sources_1/ip/ila_0/ila_0.xci}}
set_property used_in_synthesis false [get_files -all {{e:/Especializacion_fiuba/CLP/trabajo final/FIR/sintesis/filter/filter.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{e:/Especializacion_fiuba/CLP/trabajo final/FIR/sintesis/filter/filter.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{e:/Especializacion_fiuba/CLP/trabajo final/FIR/sintesis/filter/filter.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{e:/Especializacion_fiuba/CLP/trabajo final/FIR/sintesis/filter/filter.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/Especializacion_fiuba/CLP/trabajo final/FIR/src/Arty-Z7-10-Master.xdc}}
set_property used_in_implementation false [get_files {{E:/Especializacion_fiuba/CLP/trabajo final/FIR/src/Arty-Z7-10-Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top filter_VIO -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef filter_VIO.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file filter_VIO_utilization_synth.rpt -pb filter_VIO_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
